### PR TITLE
Added Styling To home Page with styles.css file

### PR DESCRIPTION
**Pull request by GAURAVKR007**
Added Styling to home page and with colorTheme [Red-black-white]
pls see through it and consider mergeing

### CODE REVIEW

**Comment by mainak2003** [comment]
@GAURAVKR007 Resolve merge conflicts!

**Comment by mainak2003** [comment]
Hey @GAURAVKR007 are you there? Please resolve the merge conflicts so that i can merge your PR too.

**Comment by GAURAVKR007** [comment]
give me some Little time

**Comment by mainak2003** [comment]
Sure @GAURAVKR007 !! Also do update the branches and then make the required changes so that merge conflicts doesn't occurs.

**Pull request closed without merging**
