### PR TITLE
Styling Added by Me 

### PR DESCRIPTION
**Pull request by GAURAVKR007**
Please Check out this Styling 
it did give me way too much of a challenge after those 10 conflicts 
i rewrite the whole code again
but did manage to save the previous one 
you can check both decide which is better.
Thanks

### CODE REVIEW

**Comment by mainak2003** [comment]
Can you share a screenshot? @GAURAVKR007

**Comment by GAURAVKR007** [comment]
image
image

**Comment by GAURAVKR007** [comment]
these are Some images of both version 
Styled by me 
please Consider it 
Thanks

**Comment by mainak2003** [comment]
Wow! Great!!

**Comment by GAURAVKR007** [comment]
Thanks

**Pull request merged**
