### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Shasg121j**
- Added cards and hover effects

### CODE REVIEW

**Comment by Shasg121j** [comment]
@mainak2003 Please review and merge it under HF

**Comment by mainak2003** [comment]
Can you once share the screenshot of what changes you have done ?

**Comment by Shasg121j** [comment]
image
I have added some cards

**Comment by mainak2003** [comment]
Great!

**Comment by Shasg121j** [comment]
Thank you

**Pull request merged**
